[package]
name = "despegate"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"
description = "Intrusive blocker that forces you to step away from the computer"

[[bin]]
name = "despegate"
path = "src/bin/despegate.rs"

[[bin]]
name = "despegated"
path = "src/bin/despegated.rs"

[[bin]]
name = "despegate-ui"
path = "src/bin/despegate-ui.rs"

[dependencies]
base64 = "0.23.1"
chrono = { version = "0.4.45", default-features = false, features = ["clock", "serde", "std"] }
clap = { version = "4.6.7", features = ["derive", "string"] }
raw-window-handle = "0.6"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tao = "0.37.1"
toml = "1.1.6"
windows-service = "0.8.1"
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_Security", "Win32_Security_Authorization", "Win32_Storage_FileSystem", "Win32_System_Diagnostics_ToolHelp", "Win32_System_IO", "Win32_System_LibraryLoader", "Win32_System_Pipes", "Win32_System_Registry", "Win32_System_RemoteDesktop", "Win32_System_Threading", "Win32_Graphics_Dwm", "Win32_Graphics_Gdi", "Win32_UI_HiDpi", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging", "Win32_System_SystemInformation", "Win32_System_Environment", "Win32_Globalization", "Win32_UI_Controls_Dialogs"] }
winreg = "0.56.0"
wry = "0.57.0"

[profile.release]
panic = "abort"

[build-dependencies]
winresource = "0.1.31"
